### PR TITLE
Initial Typescript Host Implementaton

### PR DESCRIPTION
**Pull request by jimmyaxod**
Draft PR for comments / changes.

npm install

npm run test

### CODE REVIEW

**Comment by jimmyaxod** [comment]
> Can you move the `generated.ts` file to the `generated` folder at the project root?

Will do. May need Trezy input on how to do it without breaking the build (At the moment it's complaining about node modules not found with the generated.polyglot.ts outside of ts/src etc).

**Comment by trezy** [comment]
I'm not sure I understand the testing you have set up here. Where are the test files? Or is it only testing the typings?

**Comment by jimmyaxod** [comment]
> * I'm not sure I understand the testing you have set up here. Where are the test files? Or is it only testing the typings?
> 
>     * What is the `webConfig` directory for?

There are currently 2 tests. 
* src/runtime/runtime.test.ts which tests running a couple of scale functions in a standalone context.
* src/adapters/expressAdapter.test.ts which tests running a couple of scale functions used as expressJS middleware.
The tests should run when you do `npm run test`

The webconfig directory is an alternate `package.json` which allows you to use this in a web context. I've added some very rough notes to README.md... it needs unifying with the main package.json.

NB I haven't done any typescript before, so it may be I have things in the wrong places or missed things etc

**Comment by jimmyaxod** [comment]
Obsolete

**Pull request closed without merging**
